In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np


In [5]:
a=np.array([1,2,3,4])
print(a)#one dimensional array

[1 2 3 4]


In [7]:
c=np.array(34)
c #zero dimensional array

array(34)

In [11]:
b=np.array((1,2,3,4))
print(b)

[1 2 3 4]


In [13]:
d=[6,7,8]
print(type(d))

<class 'list'>


In [15]:
print(type(a))

<class 'numpy.ndarray'>


In [17]:
print(type(c))

<class 'numpy.ndarray'>


In [25]:
r=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(r)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
s=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
s

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
g=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
g

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
h=np.array(((1,2,3),(4,5,6),(5,6,7)))
h

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7]])

In [39]:
#3-dimensional
t=np.array([[[1,2,3],[1,2,3],[2,3,4]],[[4,5,6],[6,7,8],[5,6,7]],[[1,2,3],[4,5,6],[5,6,7]]])
t

array([[[1, 2, 3],
        [1, 2, 3],
        [2, 3, 4]],

       [[4, 5, 6],
        [6, 7, 8],
        [5, 6, 7]],

       [[1, 2, 3],
        [4, 5, 6],
        [5, 6, 7]]])

In [43]:
g=np.array((((1,2),(2,4)),((4,5),(2,3)),((9,8),(6,7))))
print(g)

[[[1 2]
  [2 4]]

 [[4 5]
  [2 3]]

 [[9 8]
  [6 7]]]


In [47]:
h=np.array((((1,2,3),(2,4,7)),((4,5,6),(2,3,7)),((9,8,5),(6,7,8))))
print(h)

[[[1 2 3]
  [2 4 7]]

 [[4 5 6]
  [2 3 7]]

 [[9 8 5]
  [6 7 8]]]


In [51]:
g=np.array((((1,2),(2,4)),((4,5),(2,3)),((9,8),(6,7))))
g.ndim

3

In [60]:
a=np.array([1,2,3,4],ndmin=5)
a

array([[[[[1, 2, 3, 4]]]]])

In [62]:
a=np.array([[1,2],[3,4]],ndmin=5)
a

array([[[[[1, 2],
          [3, 4]]]]])

In [1]:
import numpy as np
a=np.array([[[1,2],[1,3]],[[1,2],[1,2]]])
print(a)

[[[1 2]
  [1 3]]

 [[1 2]
  [1 2]]]


In [3]:
a=np.array([[[1,2],[1,3]],[[1,2],[1,2]]])
a.ndim

3

In [7]:
arr=np.array([[1,2,3,4],[4,5,6,7]])
arr[0,2]

3

In [15]:
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr1[1,2]

8

In [17]:
arra3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arra3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [19]:
arra3[1,0,1]

8

In [23]:
arra3[0,1,2]

6

In [25]:
arra3[1,0,2]

9

In [27]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a[1]+b[2]

9

In [37]:
arra1=np.array([[1,2,3],[4,5,6]])
arra1


array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
arra1[0,2]+arra1[1,1]

8

In [41]:
# to get last element
a=np.array([4,5,6,7,8])
a[-1]


8

In [45]:
arra1[1,-1]

6

In [47]:
arra1[-1,-1]

6

In [51]:
arra3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arra3[0,1,-1]

6

In [57]:
aray=np.array([10,9,8,7,6])
aray[2:4]

array([8, 7])

In [61]:
aray[1:5:2]

array([9, 7])

In [63]:
aray[1:]

array([9, 8, 7, 6])

In [71]:
arra=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arra

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [75]:
arra[2,0:]

array([ 9, 10, 11, 12])

In [77]:
arra[0,:]

array([1, 2, 3, 4])

In [79]:
arra[1,1:4:2]

array([6, 8])

In [89]:
arra[0:,1:]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [91]:
arra[:,1:]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [93]:
arra[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [95]:
arra3[1,0,:]

array([7, 8, 9])

In [97]:
arra3[:,1:,2:]

array([[[ 6]],

       [[12]]])

In [103]:
arra2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arra2[2,2:4]

array([11, 12])

In [111]:
arra2[:,1:4:2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [117]:
ar2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
ar2[0,0:5:2]

array([1, 3, 5])

In [119]:
#shape:to understand the dimension of big data:
ar2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
ar2.shape


(2, 5)

In [121]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [123]:
arr3.shape

(3, 2, 3)

In [125]:
as3=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
as3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [127]:
as3.shape

(3, 2, 2)

In [137]:
#array.shape=(4,2,5)
arr4=np.array([ [[1,2,3,4,5],[6,7,8,9,10]]
               ,[[11,12,13,14,15],[16,17,18,19,20]]
               ,[[21,22,23,24,25],[26,27,28,29,30]],
               [[31,3,33,34,35],[36,37,38,39,40]],
               [[1,2,3,4,5],[6,7,8,9,10]]
              ])
arr4

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]],

       [[31,  3, 33, 34, 35],
        [36, 37, 38, 39, 40]],

       [[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [1]:
import numpy as np
#ragged matrices: there is no fixedc no. of elements


# dtypes in numpy
* i-integer
* b-boolean
* u-unsigned integer(+ ve integer)
* f-float
* c-complex float
* m-timedelta
* M-datetime
* O-object
* S-sting
* U-unicode string

In [3]:
fruits=np.array(["apple","orange","banana","mango","pineapple"])
fruits

array(['apple', 'orange', 'banana', 'mango', 'pineapple'], dtype='<U9')

In [7]:
print(type(fruits))

<class 'numpy.ndarray'>


In [11]:
fruits.dtype

dtype('<U9')

In [17]:
arr=np.array([1,2,3,4,5],dtype="c")
arr

array([b'1', b'2', b'3', b'4', b'5'], dtype='|S1')

In [19]:
arr=np.array([2,3,4,5],dtype="f")
a

array([2., 3., 4., 5.], dtype=float32)

In [21]:
arr=np.array([2,3,4,5])
arr.astype(bool)

array([ True,  True,  True,  True])

In [23]:
a=np.array(['rida','ajeeba','naseef'])
b=a.copy()
print(a)
print(b)
a[0]='ilyas'
print(a)
print(b)

['rida' 'ajeeba' 'naseef']
['rida' 'ajeeba' 'naseef']
['ilyas' 'ajeeba' 'naseef']
['rida' 'ajeeba' 'naseef']


In [25]:
a=np.array(['rida','ajeeba','naseef'])
b=a.view()

print(a)
print(b)
a[0]='ilyas'
print(a)
print(b)

['rida' 'ajeeba' 'naseef']
['rida' 'ajeeba' 'naseef']
['ilyas' 'ajeeba' 'naseef']
['ilyas' 'ajeeba' 'naseef']


In [33]:
f=np.array(['sahal','khadeeja','surumi'])
s=f.copy()
print(s)
s[1]='husna'
print(f)
print(s)

['sahal' 'khadeeja' 'surumi']
['sahal' 'khadeeja' 'surumi']
['sahal' 'husna' 'surumi']


In [35]:
f=np.array(['sahal','khadeeja','surumi'])
s=f.view()
print(s)
s[1]='husna'
print(f)
print(s)

['sahal' 'khadeeja' 'surumi']
['sahal' 'husna' 'surumi']
['sahal' 'husna' 'surumi']


In [4]:
import numpy as np
a=np.array([1,2,3,4,5,6])
b=a.copy()
c=a.view()
a[3]=6
print(a)
print(b)
print(c)

[1 2 3 6 5 6]
[1 2 3 4 5 6]
[1 2 3 6 5 6]


In [39]:
s=b.base
print(s)

None


In [6]:
print(b.base)
# if it is copy the output is none

None


In [43]:
print(c.base)
#if it is view we can see original array

[1 2 3 6 5 6]


In [47]:
arr=np.array([1,2,3,4,5],ndmin=5)
arr

array([[[[[1, 2, 3, 4, 5]]]]])

In [49]:
arr.shape# give dimension in each array

(1, 1, 1, 1, 5)

In [53]:
arr2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [55]:
arr2.shape

(3, 4)

In [59]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(a.reshape(4,3))
print(a.reshape(6,2))
print(a.reshape(3,4))
print(a.reshape(2,6))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [61]:
arr3=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr3.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [63]:
arr3.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [67]:
arr3.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [77]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
d=arr.reshape(1,3,4)
d


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [79]:
# flatening : to any dimension to one dimension.
d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [81]:
ar=np.arange(1,100)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [85]:
arr=np.arange(1,200)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [89]:
a=np.arange(1,50,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [95]:
b=np.arange(25,76)
b

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75])

In [99]:
# to make an array contain all element is 1 (ones)
z=np.ones(4,dtype='int')
z

array([1, 1, 1, 1])

In [103]:
f=np.ones((4,3),dtype='int')
f

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [105]:
q=np.ones((2,4,3),dtype='int')
q

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [107]:
#to get all item 0.
e=np.zeros(4)
e

array([0., 0., 0., 0.])

In [109]:
s=np.zeros((2,3),dtype='int')
s

array([[0, 0, 0],
       [0, 0, 0]])

In [113]:
v=np.zeros((2,3,4))
v

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [117]:
a=np.arange(0,1)
a

array([0])

In [119]:
arr=np.linspace(0,1)
arr

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [121]:
arr=np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [123]:
# represent diagonally.
a=np.array([1,2,3,4])
c=np.diag(a)
c

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [125]:
b=np.diag([1,2,3,4,5])
b

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [127]:
#eye function:to a matrix with diagonal 1:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [129]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [133]:
arra=np.array([1,2,3,4,5,6,7,8])
q=arra.reshape(2,4)
q

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [135]:
q.base

array([1, 2, 3, 4, 5, 6, 7, 8])

In [139]:
ee=np.arange(1,21)# function.
ee

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [141]:
ee.reshape((1,4,5))

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [143]:
ee.reshape(2,5,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [151]:
ass=ee.reshape(5,2,2)
ass

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20]]])

In [153]:
ass.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [1]:
import numpy as np
# mathematical operations


In [3]:
#1. sum
arr=np.array([1,2,3,4])
result=np.sum(arr)
result

10

In [5]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])
res=np.sum(arr2)
res

36

In [9]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
rslt=np.sum(arr3)
rslt

78

In [13]:
arr=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
reslt=np.add(arr,arr2)
reslt

array([ 6,  8, 10, 12])

In [15]:
tarr=np.array([[1,3,5,7],[2,4,6,8]])
tarr2=np.array([[1,2,3,4],[5,6,7,8]])
ans=np.add(tarr,tarr2)
ans

array([[ 2,  5,  8, 11],
       [ 7, 10, 13, 16]])

In [19]:
tharr=np.array([[[1,2,3],[4,5,6]],[[1,3,5],[2,4,6]]])
tharr2=np.array([[[1,2,3],[4,5,6]],[[1,3,5],[2,4,6]]])
print(np.add(tharr,tharr2))

[[[ 2  4  6]
  [ 8 10 12]]

 [[ 2  6 10]
  [ 4  8 12]]]


In [21]:
tarr=np.array([[1,3,5,7],
               [2,4,6,8]])
print(np.sum(tarr,axis=0))

[ 3  7 11 15]


In [23]:
print(np.sum(tarr,axis=1))

[16 20]


In [25]:
tharr=np.array([ [[1,2,3],[4,5,6]]
                
                 ,[[1,3,5],[2,4,6]]])
print(np.sum(tharr,axis=0))

[[ 2  5  8]
 [ 6  9 12]]


In [27]:
print(np.sum(tharr,axis=1))

[[ 5  7  9]
 [ 3  7 11]]


In [47]:
#substraction.
arr2=np.array([[1,2,3,4],[5,6,7,8]])
ar=np.array([[9,10,11,12],[13,14,15,16]])
print(np.subtract(ar,arr2))


[[8 8 8 8]
 [8 8 8 8]]


In [31]:
arr=np.array([1,2,3,4])
print(np.mean(arr))

2.5


In [33]:
print(np.max(arr))

4


In [35]:
print(np.min(arr))

1


In [37]:
print(np.std(arr))

1.118033988749895


In [41]:
a=np.array([2,4,6,8])
print(np.multiply(arr,a))


[ 2  8 18 32]


In [15]:
import numpy as np
arr=np.array([1,2,3,4,5])
for i in arr:
    print(i)

1
2
3
4
5


In [22]:
a=np.array([1,2,3,4,5,6,7,8])
for i in a:
    i+=2
    print(i)

3
4
5
6
7
8
9
10


In [11]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
for i in a:
    b=a[0:8:2]
    print(b)

[1 3 5 7]
[1 3 5 7]
[1 3 5 7]
[1 3 5 7]
[1 3 5 7]
[1 3 5 7]
[1 3 5 7]
[1 3 5 7]


In [28]:
arr=np.array([[1,2,3],[4,5,6]])
for i in arr:
    print(i)

[1 2 3]
[4 5 6]


In [56]:
i=0
n=len(a)
while i<n:
    print(a[i])
    i+=1

1
2
3
4
5


In [32]:
arr=np.array([[1,2,3],[4,5,6]])
for i in arr:
    for j in i:
        print(j)
        


1
2
3
4
5
6


In [34]:
#nditer: 
arr=np.array([[1,2,3],[4,5,6]])
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6


In [40]:
arr2=np.array([[[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12]]])
for i in np.nditer(arr2):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [42]:
# ndenumerate:
a= np.array([1,2,3,4,5])
for idx,i in np.ndenumerate(a):
    print(idx,i)


(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5


In [50]:
a2=np.array([[1,2,3],
             [4,5,6]])
for id,j in np.ndenumerate(a2):
    print(id,j)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [52]:
a3=np.array([[[1,2,3],[5,6,7]],[[8,9,0],[1,2,3]]])
for i,j in np.ndenumerate(a3):
    print(i,j)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(1, 0, 0) 8
(1, 0, 1) 9
(1, 0, 2) 0
(1, 1, 0) 1
(1, 1, 1) 2
(1, 1, 2) 3


In [58]:
#concatenate
a1=np.array([1,3,5,7,9])
a2=np.array([2,4,6,8,10])
arr=np.concatenate((a1,a2))
arr

array([ 1,  3,  5,  7,  9,  2,  4,  6,  8, 10])

In [62]:
arr1=np.array([[1,3,5],[7,8,9]])
arr2=np.array([[2,4,6],[8,10,12]])
arr=np.concatenate((arr1,arr2))
arr
                   

array([[ 1,  3,  5],
       [ 7,  8,  9],
       [ 2,  4,  6],
       [ 8, 10, 12]])

In [66]:
arrr=np.concatenate((arr1,arr2),axis=1)
arrr

array([[ 1,  3,  5,  2,  4,  6],
       [ 7,  8,  9,  8, 10, 12]])

In [15]:
import numpy as np
ara=np.array([[[1,2,3,4],[1,2,3,4]],
              [[5,6,7,8],[5,6,7,8]]])
ara1=np.array([[[2,4,6,8],[2,4,6,8]],
               [[1,3,5,7],[1,3,5,7]]])
araa=np.concatenate((ara,ara1))
araa

array([[[1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[5, 6, 7, 8],
        [5, 6, 7, 8]],

       [[2, 4, 6, 8],
        [2, 4, 6, 8]],

       [[1, 3, 5, 7],
        [1, 3, 5, 7]]])

In [17]:
araa2=np.concatenate((ara,ara1),axis=1)
araa2

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [2, 4, 6, 8],
        [2, 4, 6, 8]],

       [[5, 6, 7, 8],
        [5, 6, 7, 8],
        [1, 3, 5, 7],
        [1, 3, 5, 7]]])

In [21]:
#stack:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.vstack((arr1,arr2))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
a=np.hstack((arr1,arr2))
a

array([1, 2, 3, 4, 5, 6])

In [25]:
b=np.stack((arr1,arr2))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
c=np.dstack((arr1,arr2))
c

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [5]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[2,4],[6,8],[10,12]])
np.concatenate((a,b),axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 2,  4],
       [ 6,  8],
       [10, 12]])

In [3]:
np.concatenate((a,b),axis=1)

array([[ 1,  2,  2,  4],
       [ 3,  4,  6,  8],
       [ 5,  6, 10, 12]])

In [7]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
np.stack((arr1,arr2),axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
np.stack((arr1,arr2),axis=1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [15]:
np.stack((a,b),axis=0)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 2,  4],
        [ 6,  8],
        [10, 12]]])

In [17]:
np.stack((a,b),axis=1)

array([[[ 1,  2],
        [ 2,  4]],

       [[ 3,  4],
        [ 6,  8]],

       [[ 5,  6],
        [10, 12]]])

In [19]:
np.stack((a,b),axis=2)

array([[[ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8]],

       [[ 5, 10],
        [ 6, 12]]])

In [21]:
np.hstack((a,b))

array([[ 1,  2,  2,  4],
       [ 3,  4,  6,  8],
       [ 5,  6, 10, 12]])

In [23]:
np.vstack((a,b))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 2,  4],
       [ 6,  8],
       [10, 12]])

In [29]:
a=np.array([1,2,3,4,5,6])

np.array_split(a,4)

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [31]:
newarray=np.array_split(a,4)
newarray[0]

array([1, 2])

In [33]:
newarray[2]

array([5])

In [37]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
np.array_split(arr,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]])]

In [39]:
np.array_split(arr,2,axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [41]:
np.array_split(arr,3)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]

In [43]:
np.array_split(arr,3,axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3],
        [ 7],
        [11]]),
 array([[ 4],
        [ 8],
        [12]])]

In [45]:
# hstack:row wise data edukkum
#vstack:column wise data edukkum


In [47]:
#np.hsplit()
#np.vsplit()

In [51]:
a=np.array([1,2,3,4,5,4,3,6,7,6,8])
x=np.where(a==4)
x

(array([3, 5], dtype=int64),)

In [53]:
y=np.where(a%2==0)
y

(array([ 1,  3,  5,  7,  9, 10], dtype=int64),)

In [55]:
arr=np.array([[1,2],[3,4],[5,6],[2,5]])
np.where(arr==5)

(array([2, 3], dtype=int64), array([0, 1], dtype=int64))

In [73]:
#search_sort:
a=np.array([1,2,3,4,5,6])
np.searchsorted(a,5,side='left')

4

In [77]:
np.searchsorted(a,5,side='right')# we get the output before 

5

In [79]:
#sort:NB
a=np.array([23,45,2,36,74,5])
np.sort(a)

array([ 2,  5, 23, 36, 45, 74])

In [81]:
s=np.array(['ajeeba','sahal','khadeeja','husna','haneefa','nisha'])
np.sort(s)

array(['ajeeba', 'haneefa', 'husna', 'khadeeja', 'nisha', 'sahal'],
      dtype='<U8')

In [1]:
import numpy as np


In [3]:
pip install nbconvert

Note: you may need to restart the kernel to use updated packages.


In [11]:
!jupyter nbconvert--to html/content/numpyday1.ipynb

usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
               [--paths] [--json] [--debug]
               [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

options:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable
                 format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands: console dejavu events execute kernel kernelspec lab
labextension labhub migrate nbconvert notebook qtconsole run script server
troubleshoot trust

Jupyter command `jupyter-nbconvert--to` not found.


In [15]:
import numpy as np
#where()using condition
a=np.array([1,2,3,4,5])
b=np.where(a<4,0,a)
b

array([0, 0, 0, 4, 5])

In [17]:
a=np.array([[4,3,2,5],[3,8,7,6],[7,3,2,5]])
np.sort(a)

array([[2, 3, 4, 5],
       [3, 6, 7, 8],
       [2, 3, 5, 7]])

In [19]:
#filter function: arr is item weneed specific no. so we assign 
arr=np.array([41,42,43,44])
x=[True,False,True,False]
arr[x]

array([41, 43])

In [23]:
a=np.arange(1,11)
a
filter_arr=[]
for i in a:
    if i%2==0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
array=a[filter_arr]
array

array([ 2,  4,  6,  8, 10])

In [25]:
filter_array=a>5
new_array=a[filter_array]
new_array

array([ 6,  7,  8,  9, 10])

In [27]:
b=np.arange(1,50)
print(b)
filter_arra=[]
for i in b:
    if i%2!=0:
        filter_arra.append(True)
    else:
        filter_arra.append(False)
array=b[filter_arra]
array

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [31]:
#random numbers:
arr=np.random.rand()##to get numbers from 0 to1#based on psudo
arr

0.4009016270641943

In [35]:
a=np.random.rand(5)
a

array([0.718534  , 0.26984556, 0.29424021, 0.11768053, 0.1768377 ])

In [43]:
b=np.random.randint(1,10,5)#b=np.random.randint(1,10,size=5)
b

array([5, 8, 6, 1, 3])

In [54]:
#to avoid randomness we use seed.
np.random.seed(42)
reproducible_random_array=np.random.rand(5)
print(reproducible_random_array)

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [59]:
#to get float numbers between any number:
np.random.uniform(5)

5.290418060840997

In [61]:
np.random.uniform(5,10)

9.330880728874675

In [63]:
np.random.uniform(5,10,5)

array([8.00557506, 8.54036289, 5.10292247, 9.84954926, 9.1622132 ])

In [65]:
np.random.uniform(1,100,20)

array([22.02157196, 19.00067175, 19.15704648, 31.11998205, 52.95088673,
       43.76255685, 29.83168488, 61.57343658, 14.8098922 , 29.9223202 ,
       37.26982249, 46.15092844, 78.73242018, 20.76770443, 51.9092094 ,
       59.64904232,  5.59859086, 61.14694034, 17.88188825,  7.44010771])

In [67]:
# randn:normal distribution.
np.random.randn(100)

array([-0.60025385,  0.94743982,  0.291034  , -0.63555974, -1.02155219,
       -0.16175539, -0.5336488 , -0.00552786, -0.22945045,  0.38934891,
       -1.26511911,  1.09199226,  2.77831304,  1.19363972,  0.21863832,
        0.88176104, -1.00908534, -1.58329421,  0.77370042, -0.53814166,
       -1.3466781 , -0.88059127, -1.1305523 ,  0.13442888,  0.58212279,
        0.88774846,  0.89433233,  0.7549978 , -0.20716589, -0.62347739,
       -1.50815329,  1.09964698, -0.17773212, -0.41038331,  1.17971634,
       -0.89820794,  0.83479542,  0.29656138, -1.03782988, -0.07580375,
        0.97296353,  0.79559546,  1.49543425,  0.33818125,  3.37229625,
       -0.92039081, -0.39863839, -0.06086409, -1.41875046,  1.04249162,
        0.90353249,  0.01900033, -0.53441645, -1.49505387, -0.78925833,
        0.74371128, -0.21216142, -0.42686879,  0.50144833,  1.15818665,
        0.25711687,  0.3145129 ,  1.37186213,  0.17555329, -0.30928855,
        0.6731255 , -0.25663018, -0.36782572,  1.27373362, -0.29

In [79]:
arr=np.array([1,2,3,4,5])
np.random.shuffle(arr)
arr

array([4, 1, 5, 2, 3])