In [1]:
#numpy task 01
import numpy as np


Q1.
1-dimensional array is the collection of 0-dimensional array.
2-dimensional array is the collection of 1-dimensional array.
3-dimensional array is the collection of 2-dimensional array.


Q2. Array is a homogeneous structure.whereas list is a hetrogeneous structure.
araay has same kind of data type whereas list has different type of data type.
Array is continuous whereas list is dis countinuous.

Q3.To access get an element from a 1-dimensional array we use index position of the element..
example:


In [12]:
a=np.array([1,2,3,4,5])
a[3]

4

Q4.using arange function

In [17]:

arr=np.arange(0,21)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

Q5.using reshape function.value error will arise since we cannot convert arr into 2x3 array


In [21]:
arr=np.array([1,2,3,4,5])
arr.reshape(2,3)

ValueError: cannot reshape array of size 5 into shape (2,3)

In [24]:
#Q6.
arr=np.array([10,20,30,40,50])
arr[2]

30

In [30]:
#Q7.
arr=np.array([[[1,2,3],[2,3,4],[3,4,5]],[[4,5,6],[5,6,7],[6,7,8]]])
arr[1,2,2]

8

In [32]:
#Q8.
arr=np.array([[1,2,3],[4,5,6]])
arr.ndim

2

In [34]:
#Q9.
arr=np.array([[1,2,3],[4,5,6]])
arr[1,2]


6

In [38]:
#Q10.
arr=np.array([[1,2,3,4],[5,6,7,8]],ndmin=6)
arr

array([[[[[[1, 2, 3, 4],
           [5, 6, 7, 8]]]]]])

In [44]:
#Q11.
arr=np.array([10,20,30,40,50])
a=arr.copy()
a[4]=100
print(a)

[ 10  20  30  40 100]


In [46]:
#Q12.
a=np.array([1,2,3,4,5,6,7,8,9])
for i in a:
    if i%2==0:
        print(i)

2
4
6
8


In [50]:
#Q13.
a=np.array([1,2,3,4,5])
a[2]

3

In [62]:
#Q14.
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
c=np.where(a<3,-3,a)
print(c)
d=np.hstack((c,b))

[-3 -3  3  4  5]


In [74]:
#Q15.
a=np.arange(0,10.5,0.5)
print(a)
filter_arr=[]
for i in a:
    if i>5:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
new_arr=a[filter_arr]
new_arr

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]


array([ 5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])