#Task 02


In [9]:
import numpy as np
#Q1.
a=np.random.randint(10,50,24)
print(a)
b=a.reshape(2,3,4)
b



[26 24 42 30 49 10 16 12 19 29 15 33 15 40 35 31 36 15 18 13 38 18 49 42]


array([[[26, 24, 42, 30],
        [49, 10, 16, 12],
        [19, 29, 15, 33]],

       [[15, 40, 35, 31],
        [36, 15, 18, 13],
        [38, 18, 49, 42]]])

In [15]:
#Q2.
a=np.array([1,2,3])
b=np.array([4,5,6])
sum=np.add(a,b)
sub=np.subtract(a,b)
product=np.multiply(a,b)
quotient=np.divide(a,b)
print(sum)
print(sub)
print(product)
print(quotient)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [17]:
#Q3.
arr=np.ones((3,3),dtype='int')
arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [25]:
#Q4.
a=np.array([1,2,3,4,5,6,7,8,9])
b=a.reshape(3,3)
print(b)
c=b.reshape(-1)
print("flatten array:",c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
flatten array: [1 2 3 4 5 6 7 8 9]


In [29]:
#Q5.
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.hstack((a,b))
d=np.vstack((a,b))
print("Horizontal stack:",c)
print("Vertical satck:",d)

Horizontal stack: [[1 2 5 6]
 [3 4 7 8]]
Vertical satck: [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [31]:
#Q6.
a=np.array([1,2,3,4,5,6,7,8,9,10])
c=np.array_split(a,2)
c


[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [35]:
#Q7.
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a[1]

array([4, 5, 6])

In [37]:
#Q8.
a=np.array([10,20,30,40,50])
a[0:5:2]


array([10, 30, 50])

In [43]:
#Q9.
a=np.array([1,2,3,4,5])
sum=np.sum(a)
mean=np.mean(a)
sd=np.std(a)
print("sum of the array:",sum)
print("mean of the array:",mean)
print("standard deviation of the array:",sd)


sum of the array: 15
mean of the array: 3.0
standard deviation of the array: 1.4142135623730951


In [47]:
#Q10.
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
c=np.max(a,axis=0)
b=np.max(a,axis=1)
d=np.min(a,axis=0)
e=np.min(a,axis=1)
print(c)
print(b)
print(d)
print(e)

[7 8 9]
[3 6 9]
[1 2 3]
[1 4 7]


In [55]:
#Q11.
a=np.array([[3,1,4],[1,5,9]])
b=np.array([[2,6,5],[7,8,0]])
c=np.sort(a)
d=np.sort(b)
e=np.hstack((c,d))
e

array([[1, 3, 4, 2, 5, 6],
       [1, 5, 9, 0, 7, 8]])

In [67]:
#Q12.
a=np.array([1,2,3,4,5,6,7,8,9,10])
b=np.where(a<3)
c=np.where(a>7)
print(b)
print(c)




(array([0, 1], dtype=int64),)
(array([7, 8, 9], dtype=int64),)


In [71]:
#Q13.
a=np.array([[30,32,31,29,28,30,31],[25,26,27,28,29,30,31]])
b=np.where(a>30)
print(b)
c=np.hstack(a)
print(c)


(array([0, 0, 0, 1], dtype=int64), array([1, 2, 6, 6], dtype=int64))
[30 32 31 29 28 30 31 25 26 27 28 29 30 31]


In [73]:
#Q14.


In [75]:
#Q15.
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
filter_array=a%3==0
arr=a[filter_array]
arr


array([ 3,  6,  9, 12, 15, 18])